#!/bin/sh

# Test settings
BASE=/home/projects/benchmarks/workload
test=140_QE_CaseA_1024p
inputfile="ausurf.in"
args="-nt 4 -nk 2"
nodes=43
mpiargs="-np 1024"
failmetric=300
energy="-11427"

pbsname="$test"
if [ x"$1" != x ] ; then echo ERROR: fixed number of nodes ; exit 1 ; fi

# Environment settings
PATH="${PATH}:/app/pbs/bin:/opt/pbs/bin" ; export PATH

# Script settings
d=`date +%Y/%m/%d/%H/%M/%S`
rundir="$BASE/run/$d/$test"
datadir="$BASE/data/$test"
tmp=/scratch/projects/benchmarks/workload/$test.\$PBS_JOBID
script=run.pbs
csv="$BASE/results.csv"

# Only have one test in queue at a time
tst="" #tst=`qstat | awk '{if ( $2 == "'$pbsname'" ) {print $0}}'`
if [ x"$tst" != x ] ; then exit ; fi

# Prepare and submit test
mkdir -p $rundir && cd $rundir || exit

cat << EOF > run.pbs
#!/bin/bash
#PBS -N $pbsname
#%@FUJITSU:NSCC:CONTINUOUS_PERFORMANCE_TESTING@%#
#PBS -l select=${nodes}:ncpus=24:mpiprocs=24:ompthreads=1${SELECT_GPU}:mem=96gb
#PBS -l walltime=0:10:00
#PBS -j oe
#PBS -P 90000001

start=\`date +%s\`
# Quantum Espresso has non-zero exit code so disable exit on command error
#set -e

cd "\$PBS_O_WORKDIR" || exit \$?
mkdir $tmp
cd $tmp || exit \$?

cp -p $datadir/* .
inputfile="$inputfile"
args="$args"
module load quantum-espresso
mpirun $mpiargs pw.x \$args -i \$inputfile > stdout.\$PBS_JOBID 2>&1

mv stdout.\$PBS_JOBID "\$PBS_O_WORKDIR/"
if [ -f CRASH ] ; then mv CRASH  "\$PBS_O_WORKDIR/" ; fi
rm -f *.in *.UPF {out/,}*.wfc* {out/,}*.mix* {out/,}*.save
mv output_*.log "\$PBS_O_WORKDIR/"
rmdir out
cd "\$PBS_O_WORKDIR" || exit \$?
rmdir "$tmp" || ls "$tmp"

end=\`date +%s\`
((metric=end-start))
echo metric=\"\$metric\"

echo check time within allowable limit: $failmetric
echo metric: \$metric
if [ \$metric -gt $failmetric ] ; then echo FAIL ; exit 1 ; fi
echo check for correctness
grep "total energy              =  $energy" stdout.\$PBS_JOBID || { echo FAIL ; exit 1 ; }
echo PASS
EOF

jobid=`qsub $QSUB_ARGS run.pbs`
if [ x"$ECHO_JOBID" != x ] ; then echo $jobid ; fi
echo "$test , $jobid , Q , STIME , UNKNOWN , 0 , 00:00:00 , 0.0 , HOSTNAME , $PWD " >> "$csv"
