#!/bin/sh

# Test settings
BASE=/home/projects/benchmarks/workload
test=139_mdtest_ime_fuse
failmetric="60"

# run on any host
target=1
# run on host specified on command line
pbsname="$test"
if [ x"$1" != x ] ; then target="host=$1" ; pbsname="${test}_${1}" ; fi

# Environment settings
PATH="${PATH}:/app/pbs/bin:/opt/pbs/bin" ; export PATH

# Script settings
d=`date +%Y/%m/%d/%H/%M/%S`
rundir="$BASE/run/$d/$test"
datadir="$BASE/data/$test"
bindir="$BASE/data/bin"
tmp=tmp
script=run.pbs
csv="$BASE/results.csv"

# Only have one test in queue at a time
tst="" #tst=`qstat | awk '{if ( $2 == "'$pbsname'" ) {print $0}}'`
if [ x"$tst" != x ] ; then exit ; fi

# Prepare and submit test
mkdir -p $rundir && cd $rundir || exit

cat << EOF > run.pbs
#!/bin/bash
#PBS -N $pbsname
#%@FUJITSU:NSCC:CONTINUOUS_PERFORMANCE_TESTING@%#
#PBS -l select=${target}:ncpus=24${SELECT_GPU}:mem=96gb
#PBS -l walltime=0:30:00
#PBS -j oe
#PBS -P 90000001

failmetric="$failmetric"
module load intelmpi
PATH="/app/benchmarks/ior/bin:\$PATH" ; export PATH

echo == env
env
echo == ulimit
ulimit -a
echo == uname
uname -a

$bindir/drop_caches
memhog 95g > /dev/null

# start timing
date
start=\`date +%s\`

# start region where errors cause job to exit
set -e

if [ -d "\$PBS_O_WORKDIR" ] ; then cd "\$PBS_O_WORKDIR" ; fi
for d in /ime/projects/benchmarks/workload ; do

 # warmup
 rund=\$d/ior.\$PBS_JOBID.0
 mkdir -p \$rund
 export I_MPI_PIN_PROCESSOR=0
 mpirun -np 1 mdtest -n 10 -d \$rund -F -C -T -r -i 1 -N 1 -u > /dev/null
 rm -rf "\${rund}"

 # production
 rund=\$d/ior.\$PBS_JOBID.1
 mkdir -p \$rund
 export I_MPI_PIN_PROCESSOR=0
 mpirun -np 1 mdtest -n 1000 -d \$rund -F -C -T -r -i 10 -N 1 -u > mdtest.`uname -r`.\${d//\//_}.stdout
 rm -rf "\${rund}"

done

# end region where errors cause job to exit
set +e

# end timing
date
end=\`date +%s\`
((timing=end-start))

echo threshold for failure: \$failmetric seconds
echo time spent: \$timing seconds
echo metric=\"\$timing\"
echo \$metric | awk '{if ( \$1 > '\$failmetric' ) {printf "FAIL\n"}}' | grep FAIL && exit 1
echo \$metric | awk '{if ( \$1 <= '\$failmetric' ) {printf "PASS\n"}}' | grep PASS
EOF

jobid=`qsub $QSUB_ARGS run.pbs`
if [ x"$ECHO_JOBID" != x ] ; then echo $jobid ; fi
echo "$test , $jobid , Q , STIME , UNKNOWN , 0 , 00:00:00 , 0.0 , HOSTNAME , $PWD " >> "$csv"
