#!/bin/sh

# Test settings
BASE=/home/projects/benchmarks/workload
test=030_modules

# Environment settings
PATH="${PATH}:/app/pbs/bin:/opt/pbs/bin" ; export PATH

# Script settings
d=`date +%Y/%m/%d/%H/%M/%S`
rundir="$BASE/run/$d/$test"
datadir="$BASE/data/$test"
tmp=tmp
script=run.pbs
csv="$BASE/results.csv"

pbsname="$test"
if [ x"$1" != x ] ; then target="host=$1" ; pbsname="${test}_${1}" ; fi

# Only have one test in queue at a time
tst="" #tst=`qstat | awk '{if ( $2 == "'$test'" ) {print $0}}'`
if [ x"$tst" != x ] ; then exit ; fi

# Prepare and submit test
mkdir -p $rundir && cd $rundir || exit

cat << EOF > run.pbs
#!/bin/bash
#PBS -N $pbsname
#%@FUJITSU:NSCC:CONTINUOUS_PERFORMANCE_TESTING@%#
#PBS -l select=${target}:ncpus=24${SELECT_GPU}:mem=96gb
#PBS -l walltime=0:05:00
#PBS -j oe
#PBS -P 90000001

module purge
module avail 2>&1 | grep \$HOME/privatemodules > /dev/null && module unuse \$HOME/privatemodules
module avail

((rc=0))
module avail -t 2>&1 | grep -v '^/app.*:' | sed -e 's/(default)//' | while read module ; do
 echo == loading \$module
 module load \$module
 _rc=\`module purge && module load \$module 2>&1 | grep -c ':ERROR:'\`
 ((rc=rc+_rc))
 echo == purge \$module
 module purge
done

echo look for non-accessible files
find /app/modules >/dev/null
_rc=\$?
 ((rc=rc+_rc))

exit \$rc
EOF

jobid=`qsub $QSUB_ARGS run.pbs`
if [ x"$ECHO_JOBID" != x ] ; then echo $jobid ; fi
echo "$test , $jobid , Q , STIME , UNKNOWN , 0 , 00:00:00 , 0.0 , HOSTNAME , $PWD " >> "$csv"
