#!/bin/bash
##set -x
awk -F, '{print $1,$2,$5,$8,$10}' results.csv | while read t j s m d ; do
 if [ x"$s" == xUNKNOWN ] ; then continue ; fi
 if [ ! -d "$d" ] ; then continue ; fi
 ofile=`echo $d/${t}*.o${j%.wlm01}`
 if [ ! -f "$ofile" ] ; then continue ; fi
 unset metric
 eval $(grep ^metric= $ofile)
 if [ x"$metric" == x ] ; then continue ; fi
 if [ x"$m" != x"$metric" ] ; then echo $d ; echo $j $m $metric ; fi
done
