#!/bin/sh

# Test settings
BASE=/home/projects/benchmarks/workload
test=171_iozone_1node_data
testd=026_iozone_1node
failmetric="1500"

# run on any host
target=1
# run on host specified on command line
pbsname="$test"
if [ x"$1" != x ] ; then target="host=$1" ; pbsname="${test}_${1}" ; fi

# Environment settings
PATH="${PATH}:/app/pbs/bin:/opt/pbs/bin" ; export PATH

# Script settings
d=`date +%Y/%m/%d/%H/%M/%S`
rundir="$BASE/run/$d/$test"
datadir="$BASE/data/$testd"
tmp=tmp
script=run.pbs
csv="$BASE/results.csv"

tst=""
if [ x"$MULTI" == x ] ; then
 # Only have one test in queue at a time
 qname="${pbsname:0:15}"
 tst=`qstat | awk '{if ( $2 == "'$qname'" ) {print $0}}'`
fi
if [ x"$tst" != x ] ; then exit ; fi

# Prepare and submit test
mkdir -p $rundir && cd $rundir || exit

cat << EOF > run.pbs
#!/bin/bash
#PBS -N $pbsname
#%@FUJITSU:NSCC:CONTINUOUS_PERFORMANCE_TESTING@%#
#PBS -l select=${target}:ncpus=24${SELECT_GPU}:mem=96gb
#PBS -l walltime=1:00:00
#PBS -j oe
#PBS -P 90000001

set -e

if [ -d "\$PBS_O_WORKDIR" ] ; then cd "\$PBS_O_WORKDIR" ; fi
workdir="\$PWD"

failmetric="$failmetric"
PATH="/app/benchmarks/iozone3_471/bin:\$PATH" ; export PATH

echo == env
env
echo == ulimit
ulimit -a

$datadir/drop_caches
memhog 95g > /dev/null
for f in meminfo buddyinfo vmstat zoneinfo ; do cat /proc/\$f > proc.\$f ; done
numastat -n > numastat-n
numastat -m > numastat-m
cat /sys/kernel/debug/extfrag/extfrag_index > extfrag_index

# start timing
date
start=\`date +%s\`

cd /data/tmp && \
 iozone -Race > /dev/null && \
 for i in 0 1 2 ; do
  echo /data/tmp iteration \$i
  time iozone -Ra > "\$workdir"/iozone.gpfs.\$i
  time iozone -Race > "\$workdir"/iozone.gpfs.\$i
 done
cd "\$workdir" && rm -f /data/tmp/iozone.tmp

# end timing
date
end=\`date +%s\`
((timing=end-start))

echo time spent: \$timing seconds
echo threshold for failure: \$failmetric seconds
metric="\$timing"
echo metric=\"\$metric\"
echo \$metric | awk '{if ( \$1 > '\$failmetric' ) {printf "FAIL\n"}}' | grep FAIL && exit 1
echo \$metric | awk '{if ( \$1 <= '\$failmetric' ) {printf "PASS\n"}}' | grep PASS
EOF

jobid=`qsub $QSUB_ARGS run.pbs`
if [ x"$ECHO_JOBID" != x ] ; then echo $jobid ; fi
echo "$test , $jobid , Q , STIME , UNKNOWN , 0 , 00:00:00 , 0.0 , HOSTNAME , $PWD " >> "$csv"
