#!/bin/sh

# Test settings
BASE=/home/projects/benchmarks/workload
test=096_gromacs_2node
testd=090_gromacs_adh_cubic
#failmetric=63
failmetric=67
target=-1.3e+06
margin=1.0e+5

# default to run on any hosts
pbsname="$test"
resources="select=2:ncpus=24:mpiprocs=6:ompthreads=4${SELECT_GPU}:mem=64gb"
# run on host specified on command line
if [ $# -eq 1 ] ; then resources="select=host=${1}:ncpus=24:mpiprocs=6:ompthreads=4${SELECT_GPU}:mem=64gb+1:ncpus=24:mpiprocs=6:ompthreads=4${SELECT_GPU}:mem=64gb" ; pbsname="${test}_${1}" ; fi
if [ $# -eq 2 ] ; then resources="select=host=${1}:ncpus=24:mpiprocs=6:ompthreads=4${SELECT_GPU}:mem=64gb+host=${2}:ncpus=24:mpiprocs=6:ompthreads=4${SELECT_GPU}:mem=64gb" ; pbsname="${test}_${1}_${2}" ; fi

# Environment settings
PATH="${PATH}:/app/pbs/bin:/opt/pbs/bin" ; export PATH

# Script settings
d=`date +%Y/%m/%d/%H/%M/%S`
rundir="$BASE/run/$d/$test"
datadir="$BASE/data/$testd"
script=run.pbs
csv="$BASE/results.csv"

# Only have one test in queue at a time
tst="" #tst=`qstat | awk '{if ( $2 == "'$pbsname'" ) {print $0}}'`
if [ x"$tst" != x ] ; then exit ; fi

# Prepare and submit test
mkdir -p $rundir && cd $rundir || exit

cat << EOF > run.pbs
#!/bin/sh
#PBS -N $pbsname
#%@FUJITSU:NSCC:CONTINUOUS_PERFORMANCE_TESTING@%#
#PBS -l $resources
#PBS -l walltime=0:05:00
#PBS -j oe
#PBS -P 90000001

set -e

start=\`date +%s\`

module load gromacs/5.1.2/gcc493/impi
export I_MPI_OFA_TRANSLATION_CACHE=0
export I_MPI_DAPL_TRANSLATION_CACHE=0

cd \$PBS_O_WORKDIR
cp -p "$datadir"/* .

inputfile=pme_verlet.tpr
mpirun mdrun_mpi -pin on -ntomp \$OMP_NUM_THREADS -s "\$inputfile"
rm -f pme_verlet.tpr state.cpt confout.gro ener.edr

end=\`date +%s\`
((metric=end-start))
echo metric=\"\$metric\"

failmetric="$failmetric"
echo check time within allowable limit of \$failmetric
echo metric: \$metric
if [ \$metric -gt \$failmetric ] ; then echo FAIL ; exit 1 ; fi

echo check for correctness
target="$target"
margin="$margin"
achieved=\`grep --after-context=1 "Conserved En" md.log | tail -1 | awk '{print \$2}'\`
python -c "from sys import exit; passfail='PASS' if abs((\$achieved)-(\$target)) < \$margin else 'FAIL' ; print passfail; exit(0) if passfail == 'PASS' else exit(1);"
EOF

jobid=`qsub $QSUB_ARGS run.pbs`
if [ x"$ECHO_JOBID" != x ] ; then echo $jobid ; fi
echo "$test , $jobid , Q , STIME , UNKNOWN , 0 , 00:00:00 , 0.0 , HOSTNAME , $PWD " >> "$csv"
