#!/bin/sh

# Test settings
BASE=/home/projects/benchmarks/workload
test=142_nag_lic

# run on any host
target=1
# run on host specified on command line
pbsname="$test"
if [ x"$1" != x ] ; then target="host=$1" ; pbsname="${test}_${1}" ; fi

# Environment settings
PATH="${PATH}:/app/pbs/bin:/opt/pbs/bin" ; export PATH

# Script settings
d=`date +%Y/%m/%d/%H/%M/%S`
rundir="$BASE/run/$d/$test"
datadir="$BASE/data/$test"
script=run.pbs
csv="$BASE/results.csv"

# Only have one test in queue at a time
tst="" #tst=`qstat | awk '{if ( $2 == "'$pbsname'" ) {print $0}}'`
if [ x"$tst" != x ] ; then exit ; fi

# Prepare and submit test
mkdir -p $rundir && cd $rundir || exit

cat << EOF > run.pbs
#!/bin/bash
#PBS -N $pbsname
#%@FUJITSU:NSCC:CONTINUOUS_PERFORMANCE_TESTING@%#
#PBS -l select=${target}:ncpus=1${SELECT_GPU}:mem=1gb
#PBS -l walltime=0:05:00
#PBS -j oe
#PBS -P 90000001
if [ -d "\$PBS_O_WORKDIR" ] ; then cd "\$PBS_O_WORKDIR" ; fi

module load intelcc
module load nag-libraries
cp -p /app/NAG/nagdoc_fl24/examples/source/a00acfe.f90 .
ifort -mkl a00acfe.f90 -o a00acfe.x -I /app/NAG/fll6i25dcl/nag_interface_blocks  /app/NAG/fll6i25dcl/lib/libnag_mkl.a
./a00acfe.x
./a00acfe.x | grep "A valid licence key is available" > /dev/null || { rc=\$? ; echo rc=\$rc ; echo FAIL ; exit \$rc ; }
unset NAG_KUSARI_FILE
./a00acfe.x
./a00acfe.x | grep "No valid licence key was found" > /dev/null || { rc=\$? ; echo rc=\$rc ; echo FAIL ; exit \$rc ; }

module load nag-compiler
cat << EOD > hello_world.f
      program world
       print *,'hello world'
      stop
      end
EOD
nagfor hello_world.f -o hello_world.x || { rc=\$? ; rm -f hello_world.x ; echo rc=\$rc ; echo FAIL ; exit \$rc ; }
rm -f hello_world.x
echo PASS
EOF

jobid=`qsub $QSUB_ARGS run.pbs`
if [ x"$ECHO_JOBID" != x ] ; then echo $jobid ; fi
echo "$test , $jobid , Q , STIME , UNKNOWN , 0 , 00:00:00 , 0.0 , HOSTNAME , $PWD " >> "$csv"
