#!/bin/sh

# Test settings
BASE=/home/projects/benchmarks/workload
test=054_linpack_local
testd=050_linpack
failmetric=700.0

# run on any host
target=1
# run on host specified on command line
pbsname="$test"
if [ x"$1" != x ] ; then target="host=$1" ; pbsname="${test}_${1}" ; fi

# Environment settings
PATH="${PATH}:/app/pbs/bin:/opt/pbs/bin" ; export PATH

# Script settings
d=`date +%Y/%m/%d/%H/%M/%S`
rundir="$BASE/run/$d/$test"
datadir="$BASE/data/$testd"
tmp="/dev/shm/tmp.$LOGNAME.$$"
script=run.pbs
csv="$BASE/results.csv"

tst=""
if [ x"$MULTI" == x ] ; then
 # Only have one test in queue at a time
 tst=`qstat | awk '{if ( $2 == "'$pbsname'" ) {print $0}}'`
fi
if [ x"$tst" != x ] ; then exit ; fi

# Prepare and submit test
mkdir -p $rundir && cd $rundir || exit

cat << EOF > run.pbs
#!/bin/bash
#PBS -N $pbsname
#%@FUJITSU:NSCC:CONTINUOUS_PERFORMANCE_TESTING@%#
#PBS -l select=${target}:ncpus=24:mem=96gb
#PBS -l walltime=1:00:00
#PBS -j oe
#PBS -P 90000001

set -e

failmetric="$failmetric"
if [ -d "\$PBS_O_WORKDIR" ] ; then cd "\$PBS_O_WORKDIR" ; fi
workdir="\$PWD"

unset OMP_NUM_THREADS
export KMP_AFFINITY="granularity=fine,compact"

echo copy executable and input files to in-memory filesystem
mkdir "$tmp"
cd "$tmp"
module load composerxe
cp -p "\$MKLROOT/benchmarks/linpack/xlinpack_xeon64" ./
module purge
cp -p "$datadir/lininput_warmup" "$datadir/lininput_production" ./

echo clean node memory
$datadir/drop_caches
memhog 90g > /dev/null
for f in meminfo buddyinfo vmstat zoneinfo ; do cat /proc/\$f > proc.\$f ; done
numastat -n > numastat-n
numastat -m > numastat-m
cat /sys/kernel/debug/extfrag/extfrag_index > extfrag_index

echo run warmup
nohup "./xlinpack_xeon64" lininput_warmup < /dev/null > /dev/null 2>&1
echo run production
nohup "./xlinpack_xeon64" lininput_production < /dev/null > xlinpack_xeon64.\$PBS_JOBID.stdout 2>&1

echo transfer back output to permanent storage
mv xlinpack_xeon64.\$PBS_JOBID.stdout "\$workdir/"
cd "\$workdir"
echo remove temporary directory
rm -rf "$tmp"

metric=\`grep "^96000 .* pass$" xlinpack_xeon64.\$PBS_JOBID.stdout | awk '{print \$5}'\`
echo metric=\"\$metric\"

echo check residual
grep '^Residual checks' xlinpack_xeon64.\$PBS_JOBID.stdout
grep '^Residual checks PASSED' xlinpack_xeon64.\$PBS_JOBID.stdout

echo check for throttling
dmesg  | grep "Package temperature above threshold" && echo FAIL && exit 1 || echo OK

echo check performance
echo metric: \$metric
echo \$metric | awk '{if ( \$1 > '\$failmetric' ) {printf "PASS\n"}}' | grep PASS
EOF

jobid=`qsub $QSUB_ARGS run.pbs`
if [ x"$ECHO_JOBID" != x ] ; then echo $jobid ; fi
echo "$test , $jobid , Q , STIME , UNKNOWN , 0 , 00:00:00 , 0.0 , HOSTNAME , $PWD " >> "$csv"
