#!/bin/sh

# Test settings
BASE=/home/projects/benchmarks/workload
test=133_qsub
failmetric="120"

# run on any host
target=1
# run on host specified on command line
pbsname="$test"
if [ x"$1" != x ] ; then target="host=$1" ; pbsname="${test}_${1}" ; fi

# Environment settings
PATH="${PATH}:/app/pbs/bin:/opt/pbs/bin" ; export PATH

# Script settings
d=`date +%Y/%m/%d/%H/%M/%S`
rundir="$BASE/run/$d/$test"
bindir="$BASE/data/bin"
tmp=tmp
script=run.pbs
csv="$BASE/results.csv"

if [ x"$SINGLE" != x ] ; then
# Only have one test in queue at a time
qname="${pbsname:0:15}"
tst=`qstat | awk '{if ( $2 == "'$qname'" ) {print $0}}'`
if [ x"$tst" != x ] ; then exit ; fi
fi

# Prepare and submit test
mkdir -p $rundir && cd $rundir || exit

cat << EOF > run.pbs
#!/bin/bash
#PBS -N $pbsname
#%@FUJITSU:NSCC:CONTINUOUS_PERFORMANCE_TESTING@%#
#PBS -l select=${target}:ncpus=1${SELECT_GPU}:mem=1gb
#PBS -l walltime=00:30:00
#PBS -j oe
#PBS -P 90000001

if [ -d "\$PBS_O_WORKDIR" ] ; then cd "\$PBS_O_WORKDIR" ; fi
echo check direct command
date
start=\`date +%s\`
echo true | /opt/pbs/bin/qsub -l select=1:ncpus=1:mem=1g -l walltime=0:01:00 -N qsub -j oe -P 90000001 || { echo FAIL ; exit 1 ; }
end=\`date +%s\`
date
((metric=end-start))
echo metric=\"\$metric\"

echo check wrapper
date
start=\`date +%s\`
echo true | /app/pbs/bin/qsub -l select=1:ncpus=1:mem=1g -l walltime=0:01:00 -N qsub -j oe -P 90000001 || { echo FAIL ; exit 1 ; }
end=\`date +%s\`
date
((wrapper=end-start))
echo wrapper=\"\$wrapper\"

failmetric=$failmetric
echo threshold for failure: \$failmetric seconds
echo metric: \$metric
echo \$metric | awk '{if ( \$1 > '\$failmetric' ) {printf "FAIL\n"}}' | grep FAIL && exit 1
echo \$metric | awk '{if ( \$1 <= '\$failmetric' ) {printf "PASS\n"}}' | grep PASS
EOF

jobid=`qsub $QSUB_ARGS run.pbs`
if [ x"$ECHO_JOBID" != x ] ; then echo $jobid ; fi
if [ x"$jobid" != x ] ; then
 echo "$test , $jobid , Q , STIME , UNKNOWN , 0 , 00:00:00 , 0.0 , HOSTNAME , $PWD " >> "$csv"
else
 echo "$test , NA , F , "`date +"%a %b %d %H:%M:%S %Y"`" , FAIL , 1 , 00:00:00 , 0.0 , NA , $PWD " >> "$csv"
fi
