#!/bin/sh

# Test settings
BASE=/home/projects/benchmarks/workload
test=010_compile
#failmetric=1650
failmetric=2500

# run on any host
target=1
# run on host specified on command line
pbsname="$test"
if [ x"$1" != x ] ; then target="host=$1" ; pbsname="${test}_${1}" ; fi

# Environment settings
PATH="${PATH}:/app/pbs/bin:/opt/pbs/bin" ; export PATH

# Script settings
d=`date +%Y/%m/%d/%H/%M/%S`
rundir="$BASE/run/$d/$test"
datadir="$BASE/data/$test"
script=run.pbs
csv="$BASE/results.csv"

# Only have one test in queue at a time
tst="" #tst=`qstat | awk '{if ( $2 == "'$pbsname'" ) {print $0}}'`
if [ x"$tst" != x ] ; then exit ; fi

# Prepare and submit test
mkdir -p $rundir && cd $rundir || exit

cat << EOF > run.pbs
#!/bin/bash
#PBS -N $pbsname
#%@FUJITSU:NSCC:CONTINUOUS_PERFORMANCE_TESTING@%#
#PBS -l select=${target}:ncpus=24${SELECT_GPU}:mem=96gb
#PBS -l walltime=1:00:00
#PBS -j oe
#PBS -P 90000001

set -e

start=\`date +%s\`

cd "\$PBS_O_WORKDIR"

rc=0
v=5.4.0
module load composerxe/2017.0.098
export PATH="\$PATH:/app/nsccadmin/bin"
lmstat -a
tar zxf $datadir/espresso-\$v.tar.gz && \
 cd espresso-\$v && \
 ./configure --enable-openmp --enable-parallel --with-scalapack=intel && \
 make all || rc=$?

cd "\$PBS_O_WORKDIR" && rm -rf espresso-\$v
lmstat -a

end=\`date +%s\`
((metric=end-start))
echo metric=\"\$metric\"

failmetric="$failmetric"
echo failmetric: \$failmetric
echo metric: \$metric
if [ \$metric -gt \$failmetric ] ; then echo FAIL ; exit 1 ; fi
exit $rc
EOF

jobid=`qsub $QSUB_ARGS run.pbs`
if [ x"$ECHO_JOBID" != x ] ; then echo $jobid ; fi
echo "$test , $jobid , Q , STIME , UNKNOWN , 0 , 00:00:00 , 0.0 , HOSTNAME , $PWD " >> "$csv"
